#!/usr/bin/env python
"""
Performs energy mix optimization using Linear Programming (Scipy Linprog).

This script simplifies the problem by using annual average generation potentials
and does NOT explicitly model battery storage dynamics. It optimizes the *annual energy contribution*
from PV, Wind, and Grid to meet a target annual demand while respecting land constraints
and minimizing total annual GWP.
"""

import pandas as pd
import numpy as np
from scipy.optimize import linprog
import sys
import os

# --- Configuration ---
# GWP Factors (kg CO2e/kWh)
GWP_PV = 0.07
GWP_WIND = 0.011
GWP_GRID = 0.6

# Land Use Factors (km²/MW)
PV_LAND_PER_MW = 0.02
WIND_LAND_PER_MW = 0.26

# Constraints
# AVAILABLE_LAND_KM2 = 50 # Original
AVAILABLE_LAND_KM2 = 1000 # User specified for last run

# Input file containing hourly potentials per MW
POTENTIALS_CSV = os.path.join('output_data', 'australian_energy_data_potentials.csv')

HOURS_PER_YEAR = 8760

def run_linear_programming_optimization(annual_demand_mwh):
    """
    Runs the LP optimization.

    Args:
        annual_demand_mwh (float): Target annual energy demand in MWh.

    Returns:
        dict: A dictionary containing the optimization results, or None if failed.
    """
    print("--- Starting Linear Programming Optimization ---")
    print(f"Target Annual Demand: {annual_demand_mwh} MWh")
    print(f"Available Land: {AVAILABLE_LAND_KM2} km²")
    print(f"GWP Factors (kg CO2e/kWh): PV={GWP_PV}, Wind={GWP_WIND}, Grid={GWP_GRID}")
    print("NOTE: This LP model uses annual averages and ignores battery storage.")

    annual_demand_kwh = annual_demand_mwh * 1000

    # --- Load and Process Potential Data ---
    try:
        potentials_df = pd.read_csv(POTENTIALS_CSV)
        print(f"Loaded potential data from {POTENTIALS_CSV}")
    except FileNotFoundError:
        print(f"Error: Input file not found: {POTENTIALS_CSV}")
        print("Please run the simulation script ('run_optimization.py') first to generate it.")
        return None
    except Exception as e:
        print(f"Error reading {POTENTIALS_CSV}: {e}")
        return None

    # Calculate average hourly potential per MW (kWh/MW/hour)
    avg_pv_potential_kwh_per_mw_hr = potentials_df['pv_potential_per_mw'].mean()
    avg_wind_potential_kwh_per_mw_hr = potentials_df['wind_potential_per_mw'].mean()

    print(f"Average Hourly Potential (kWh/MW/h): PV={avg_pv_potential_kwh_per_mw_hr:.4f}, Wind={avg_wind_potential_kwh_per_mw_hr:.4f}")

    # Avoid division by zero if potential is zero or negative
    if avg_pv_potential_kwh_per_mw_hr <= 1e-6: # Use a small epsilon
         print("Warning: Average PV potential is near zero. PV capacity calculation might be unstable.")
         # Effectively infinite land use per kWh
         pv_km2_per_kwh = np.inf
    else:
         # Calculate land required per annual kWh generated by PV
         # (km²/MW) / (kWh/MW/year) = km²/kWh
         pv_annual_kwh_per_mw = avg_pv_potential_kwh_per_mw_hr * HOURS_PER_YEAR
         pv_km2_per_kwh = PV_LAND_PER_MW / pv_annual_kwh_per_mw

    if avg_wind_potential_kwh_per_mw_hr <= 1e-6:
        print("Warning: Average Wind potential is near zero. Wind capacity calculation might be unstable.")
        wind_km2_per_kwh = np.inf
    else:
        # Calculate land required per annual kWh generated by Wind
        wind_annual_kwh_per_mw = avg_wind_potential_kwh_per_mw_hr * HOURS_PER_YEAR
        wind_km2_per_kwh = WIND_LAND_PER_MW / wind_annual_kwh_per_mw

    print(f"Land Use per Annual kWh (km²/kWh): PV={pv_km2_per_kwh:.8e}, Wind={wind_km2_per_kwh:.8e}")

    # --- Define the Linear Program ---
    # Decision variables (y):
    # y[0] = Annual kWh from PV (e_pv)
    # y[1] = Annual kWh from Wind (e_wind)
    # y[2] = Annual kWh from Grid (e_grid)

    # Objective function coefficients (c): Minimize total GWP
    c = [GWP_PV, GWP_WIND, GWP_GRID]

    # Equality constraints (A_eq * y = b_eq)
    # 1. Meet annual demand: e_pv + e_wind + e_grid = annual_demand_kwh
    A_eq = [[1, 1, 1]]
    b_eq = [annual_demand_kwh]

    # Inequality constraints (A_ub * y <= b_ub)
    # 1. Land use: (e_pv * pv_km2_per_kwh) + (e_wind * wind_km2_per_kwh) <= available_land_km2
    #    Note: Grid energy (y[2]) does not use land in this model.
    A_ub = [[pv_km2_per_kwh, wind_km2_per_kwh, 0]]
    b_ub = [AVAILABLE_LAND_KM2]

    # Bounds for decision variables (must be non-negative)
    bounds = [(0, None), (0, None), (0, None)] # (e_pv >= 0, e_wind >= 0, e_grid >= 0)

    # --- Solve the Linear Program ---
    print("Solving LP using SciPy...")
    try:
        result = linprog(c, A_eq=A_eq, b_eq=b_eq, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method='highs') # 'highs' is recommended
    except ValueError as e:
        print(f"Error during LP solving: {e}")
        print("This might happen if constraints are impossible (e.g., infinite land use due to zero potential).")
        return None


    # --- Process Results ---
    if result.success:
        e_pv, e_wind, e_grid = result.x
        total_gwp = result.fun
        total_energy_supplied = e_pv + e_wind + e_grid # Should match demand

        # Calculate approximate capacities needed (MW)
        pv_capacity_mw = 0
        if avg_pv_potential_kwh_per_mw_hr > 1e-6:
             pv_capacity_mw = e_pv / (avg_pv_potential_kwh_per_mw_hr * HOURS_PER_YEAR)

        wind_capacity_mw = 0
        if avg_wind_potential_kwh_per_mw_hr > 1e-6:
             wind_capacity_mw = e_wind / (avg_wind_potential_kwh_per_mw_hr * HOURS_PER_YEAR)

        # Calculate land used
        land_used_pv = pv_capacity_mw * PV_LAND_PER_MW
        land_used_wind = wind_capacity_mw * WIND_LAND_PER_MW
        total_land_used = land_used_pv + land_used_wind

        # Calculate average GWP per kWh
        avg_gwp_per_kwh = total_gwp / total_energy_supplied if total_energy_supplied > 0 else 0

        # Store results
        results = {
            'success': True,
            'annual_demand_kwh': annual_demand_kwh,
            'e_pv_kwh': e_pv,
            'e_wind_kwh': e_wind,
            'e_grid_kwh': e_grid,
            'pv_capacity_mw': pv_capacity_mw,
            'wind_capacity_mw': wind_capacity_mw,
            'land_used_pv_km2': land_used_pv,
            'land_used_wind_km2': land_used_wind,
            'total_land_used_km2': total_land_used,
            'total_gwp_kg_co2e': total_gwp,
            'avg_gwp_per_kwh': avg_gwp_per_kwh
        }
        print("LP Optimization Successful.")
        return results

    else:
        print(f"LP Optimization Failed. Status: {result.status}, Message: {result.message}")
        return {'success': False, 'message': result.message}


if __name__ == "__main__":
    # --- Get User Input for Annual Demand ---
    while True:
        try:
            user_demand_mwh = float(input(f"Enter the target annual energy demand in MWh (using {AVAILABLE_LAND_KM2} km² land): "))
            if user_demand_mwh > 0:
                break
            else:
                print("Demand must be a positive number.")
        except ValueError:
            print("Invalid input. Please enter a number.")

    results = run_linear_programming_optimization(user_demand_mwh)

    if results and results['success']:
        print("\n--- LP Optimization Results ---")
        print(f"Target Annual Demand: {results['annual_demand_kwh']/1e6:,.2f} GWh")
        print("Optimal Annual Energy Contributions:")
        print(f"  PV:   {results['e_pv_kwh']/1e6:,.2f} GWh ({results['e_pv_kwh']/results['annual_demand_kwh']*100:.1f}%)")
        print(f"  Wind: {results['e_wind_kwh']/1e6:,.2f} GWh ({results['e_wind_kwh']/results['annual_demand_kwh']*100:.1f}%)")
        print(f"  Grid: {results['e_grid_kwh']/1e6:,.2f} GWh ({results['e_grid_kwh']/results['annual_demand_kwh']*100:.1f}%)")
        print("\nEstimated Capacities Required:")
        print(f"  PV Capacity:   {results['pv_capacity_mw']:,.1f} MW")
        print(f"  Wind Capacity: {results['wind_capacity_mw']:,.1f} MW")
        print("\nLand Use:")
        print(f"  PV Land:   {results['land_used_pv_km2']:,.2f} km²")
        print(f"  Wind Land: {results['land_used_wind_km2']:,.2f} km²")
        print(f"  Total Land: {results['total_land_used_km2']:,.2f} km² (Limit: {AVAILABLE_LAND_KM2:,.2f} km²)")
        print("\nOptimized GWP:")
        print(f"  Minimum Average GWP: {results['avg_gwp_per_kwh']:.4f} kg CO2e/kWh")
        print(f"  Total Annual GWP: {results['total_gwp_kg_co2e']/1e6:,.2f} million kg CO2e")

    elif results:
        print(f"\nLP Optimization could not find a solution: {results['message']}")
    else:
        print("\nLP Optimization failed to run due to input errors.")

    print("\n--- LP Optimization Complete ---") 